// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_screen_screen_init(void)
{
ui_screen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container12 = lv_obj_create(ui_screen);
lv_obj_remove_style_all(ui_Container12);
lv_obj_set_width( ui_Container12, lv_pct(100));
lv_obj_set_height( ui_Container12, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Container12, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_Container12,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container12, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container12, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container12, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container12, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container8 = lv_obj_create(ui_Container12);
lv_obj_remove_style_all(ui_Container8);
lv_obj_set_width( ui_Container8, lv_pct(100));
lv_obj_set_height( ui_Container8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Container8, 0 );
lv_obj_set_y( ui_Container8, 5 );
lv_obj_set_align( ui_Container8, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_Container8,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_pad_left(ui_Container8, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container8, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container8, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container8, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_duration = lv_label_create(ui_Container8);
lv_obj_set_height( ui_duration, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_grow( ui_duration, 1);
lv_obj_set_x( ui_duration, 5 );
lv_obj_set_y( ui_duration, 5 );
lv_label_set_text(ui_duration,"----");
lv_obj_set_style_text_align(ui_duration, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_duration, &ui_font_lato22, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_duration, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_duration, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_duration, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_duration, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_curtime = lv_label_create(ui_Container8);
lv_obj_set_width( ui_curtime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_curtime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_curtime, -5 );
lv_obj_set_y( ui_curtime, 5 );
lv_obj_set_align( ui_curtime, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_curtime,"0:00am");
lv_obj_set_scrollbar_mode(ui_curtime, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_font(ui_curtime, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_curtime, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_USER_1);

ui_currentActivity = lv_img_create(ui_Container12);
lv_obj_set_width( ui_currentActivity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_currentActivity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_currentActivity, 0 );
lv_obj_set_y( ui_currentActivity, -140 );
lv_obj_set_align( ui_currentActivity, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_currentActivity, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_currentActivity, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_eventTitle = lv_label_create(ui_Container12);
lv_obj_set_width( ui_eventTitle, lv_pct(100));
lv_obj_set_height( ui_eventTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_eventTitle, 0 );
lv_obj_set_y( ui_eventTitle, -165 );
lv_obj_set_align( ui_eventTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_eventTitle,"----");
lv_obj_set_style_text_align(ui_eventTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_eventTitle, &ui_font_lato22, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_eventTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_eventTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_eventTitle, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_eventTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_forecasts = lv_obj_create(ui_screen);
lv_obj_remove_style_all(ui_forecasts);
lv_obj_set_height( ui_forecasts, 120);
lv_obj_set_width( ui_forecasts, lv_pct(100));
lv_obj_set_align( ui_forecasts, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_forecasts,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_forecasts, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_forecasts, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container9 = lv_obj_create(ui_forecasts);
lv_obj_remove_style_all(ui_Container9);
lv_obj_set_height( ui_Container9, lv_pct(100));
lv_obj_set_width( ui_Container9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Container9, -108 );
lv_obj_set_y( ui_Container9, 166 );
lv_obj_set_align( ui_Container9, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container9,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_futureDOW1 = lv_label_create(ui_Container9);
lv_obj_set_width( ui_futureDOW1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_futureDOW1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_futureDOW1, -30 );
lv_obj_set_y( ui_futureDOW1, 117 );
lv_obj_set_align( ui_futureDOW1, LV_ALIGN_CENTER );
lv_label_set_text(ui_futureDOW1,"---");
lv_obj_set_style_text_font(ui_futureDOW1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_futureCond1 = lv_img_create(ui_Container9);
lv_obj_set_width( ui_futureCond1, 45);
lv_obj_set_height( ui_futureCond1, 45);
lv_obj_set_x( ui_futureCond1, -99 );
lv_obj_set_y( ui_futureCond1, 143 );
lv_obj_set_align( ui_futureCond1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_futureCond1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_futureCond1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_futureHL1 = lv_label_create(ui_Container9);
lv_obj_set_width( ui_futureHL1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_futureHL1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_futureHL1, -30 );
lv_obj_set_y( ui_futureHL1, 117 );
lv_obj_set_align( ui_futureHL1, LV_ALIGN_CENTER );
lv_label_set_text(ui_futureHL1,"---");
lv_obj_set_style_text_align(ui_futureHL1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_futureHL1, &ui_font_lato14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container3 = lv_obj_create(ui_forecasts);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_height( ui_Container3, lv_pct(100));
lv_obj_set_width( ui_Container3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Container3, -107 );
lv_obj_set_y( ui_Container3, 166 );
lv_obj_set_align( ui_Container3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container3,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_futureDOW2 = lv_label_create(ui_Container3);
lv_obj_set_width( ui_futureDOW2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_futureDOW2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_futureDOW2, -30 );
lv_obj_set_y( ui_futureDOW2, 117 );
lv_obj_set_align( ui_futureDOW2, LV_ALIGN_CENTER );
lv_label_set_text(ui_futureDOW2,"---");
lv_obj_set_style_text_font(ui_futureDOW2, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_futureCond2 = lv_img_create(ui_Container3);
lv_obj_set_width( ui_futureCond2, 45);
lv_obj_set_height( ui_futureCond2, 45);
lv_obj_set_x( ui_futureCond2, -99 );
lv_obj_set_y( ui_futureCond2, 143 );
lv_obj_set_align( ui_futureCond2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_futureCond2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_futureCond2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_futureHL2 = lv_label_create(ui_Container3);
lv_obj_set_width( ui_futureHL2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_futureHL2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_futureHL2, -30 );
lv_obj_set_y( ui_futureHL2, 117 );
lv_obj_set_align( ui_futureHL2, LV_ALIGN_CENTER );
lv_label_set_text(ui_futureHL2,"---");
lv_obj_set_style_text_align(ui_futureHL2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_futureHL2, &ui_font_lato14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container10 = lv_obj_create(ui_forecasts);
lv_obj_remove_style_all(ui_Container10);
lv_obj_set_height( ui_Container10, lv_pct(100));
lv_obj_set_width( ui_Container10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Container10, -107 );
lv_obj_set_y( ui_Container10, 166 );
lv_obj_set_align( ui_Container10, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container10,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_futureDOW3 = lv_label_create(ui_Container10);
lv_obj_set_width( ui_futureDOW3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_futureDOW3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_futureDOW3, -30 );
lv_obj_set_y( ui_futureDOW3, 117 );
lv_obj_set_align( ui_futureDOW3, LV_ALIGN_CENTER );
lv_label_set_text(ui_futureDOW3,"---");
lv_obj_set_style_text_font(ui_futureDOW3, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_futureCond3 = lv_img_create(ui_Container10);
lv_obj_set_width( ui_futureCond3, 45);
lv_obj_set_height( ui_futureCond3, 45);
lv_obj_set_x( ui_futureCond3, -99 );
lv_obj_set_y( ui_futureCond3, 143 );
lv_obj_set_align( ui_futureCond3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_futureCond3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_futureCond3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_futureHL3 = lv_label_create(ui_Container10);
lv_obj_set_width( ui_futureHL3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_futureHL3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_futureHL3, -30 );
lv_obj_set_y( ui_futureHL3, 117 );
lv_obj_set_align( ui_futureHL3, LV_ALIGN_CENTER );
lv_label_set_text(ui_futureHL3,"---");
lv_obj_set_style_text_align(ui_futureHL3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_futureHL3, &ui_font_lato14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container11 = lv_obj_create(ui_forecasts);
lv_obj_remove_style_all(ui_Container11);
lv_obj_set_height( ui_Container11, lv_pct(100));
lv_obj_set_width( ui_Container11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Container11, -107 );
lv_obj_set_y( ui_Container11, 166 );
lv_obj_set_align( ui_Container11, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container11,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_futureDOW4 = lv_label_create(ui_Container11);
lv_obj_set_width( ui_futureDOW4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_futureDOW4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_futureDOW4, -30 );
lv_obj_set_y( ui_futureDOW4, 117 );
lv_obj_set_align( ui_futureDOW4, LV_ALIGN_CENTER );
lv_label_set_text(ui_futureDOW4,"---");
lv_obj_set_style_text_font(ui_futureDOW4, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_futureCond4 = lv_img_create(ui_Container11);
lv_obj_set_width( ui_futureCond4, 45);
lv_obj_set_height( ui_futureCond4, 45);
lv_obj_set_x( ui_futureCond4, -99 );
lv_obj_set_y( ui_futureCond4, 143 );
lv_obj_set_align( ui_futureCond4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_futureCond4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_futureCond4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_futureHL4 = lv_label_create(ui_Container11);
lv_obj_set_width( ui_futureHL4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_futureHL4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_futureHL4, -30 );
lv_obj_set_y( ui_futureHL4, 117 );
lv_obj_set_align( ui_futureHL4, LV_ALIGN_CENTER );
lv_label_set_text(ui_futureHL4,"---");
lv_obj_set_style_text_align(ui_futureHL4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_futureHL4, &ui_font_lato14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_current = lv_obj_create(ui_screen);
lv_obj_remove_style_all(ui_current);
lv_obj_set_width( ui_current, lv_pct(100));
lv_obj_set_height( ui_current, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_current, 0 );
lv_obj_set_y( ui_current, 50 );
lv_obj_set_align( ui_current, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_current,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_current, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_current, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_current, lv_color_hex(0x565656), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_current, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_current, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_current, LV_BORDER_SIDE_TOP, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_current, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_current, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_current, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_current, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_current, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_current, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_current, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_current, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_forecastConditionsDesc = lv_label_create(ui_current);
lv_obj_set_width( ui_forecastConditionsDesc, lv_pct(100));
lv_obj_set_height( ui_forecastConditionsDesc, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_forecastConditionsDesc, -4 );
lv_obj_set_y( ui_forecastConditionsDesc, 248 );
lv_obj_set_align( ui_forecastConditionsDesc, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_forecastConditionsDesc,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_forecastConditionsDesc, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_forecastConditionsDesc,"----");
lv_obj_set_style_text_align(ui_forecastConditionsDesc, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_forecastConditionsDesc, &ui_font_lato14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_forecastConditionsDesc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_forecastConditionsDesc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_forecastConditionsDesc, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_forecastConditionsDesc, -5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_hourlyForecastChart = lv_chart_create(ui_current);
lv_obj_set_height( ui_hourlyForecastChart, 25);
lv_obj_set_width( ui_hourlyForecastChart, lv_pct(100));
lv_obj_set_x( ui_hourlyForecastChart, 0 );
lv_obj_set_y( ui_hourlyForecastChart, -81 );
lv_obj_set_align( ui_hourlyForecastChart, LV_ALIGN_TOP_MID );
lv_chart_set_type( ui_hourlyForecastChart, LV_CHART_TYPE_BAR);
lv_chart_set_point_count( ui_hourlyForecastChart, 60);
lv_chart_set_range( ui_hourlyForecastChart, LV_CHART_AXIS_PRIMARY_Y, 20, 100);
lv_chart_set_div_line_count( ui_hourlyForecastChart, 3, 0);
lv_chart_set_zoom_x( ui_hourlyForecastChart, 256);
lv_chart_set_zoom_y( ui_hourlyForecastChart, 600);
lv_chart_set_axis_tick( ui_hourlyForecastChart, LV_CHART_AXIS_PRIMARY_X, 2, 0, 5, 4, true, 14);
lv_chart_set_axis_tick( ui_hourlyForecastChart, LV_CHART_AXIS_PRIMARY_Y, 20, 1, 0, 0, false, 20);
lv_chart_set_axis_tick( ui_hourlyForecastChart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 0, 0, false, 25);
lv_obj_set_style_bg_color(ui_hourlyForecastChart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_hourlyForecastChart, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_hourlyForecastChart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_hourlyForecastChart, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_line_color(ui_hourlyForecastChart, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_hourlyForecastChart, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_hourlyForecastChart, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_hourlyForecastChart, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_hourlyForecastChart, 0, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_hourlyForecastChart, 0, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_hourlyForecastChart, 15, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_hourlyForecastChart, 0, LV_PART_ITEMS| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_hourlyForecastChart, &lv_font_montserrat_14, LV_PART_TICKS| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_current);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, lv_pct(100));
lv_obj_set_height( ui_Container1, LV_SIZE_CONTENT);   /// 60
lv_obj_set_x( ui_Container1, 0 );
lv_obj_set_y( ui_Container1, 60 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_currentWeather = lv_img_create(ui_Container1);
lv_obj_set_width( ui_currentWeather, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_currentWeather, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_currentWeather, -70 );
lv_obj_set_y( ui_currentWeather, 37 );
lv_obj_set_align( ui_currentWeather, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_currentWeather,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_currentWeather, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_currentWeather, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_currentWeather, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_currentWeather, LV_SCROLLBAR_MODE_OFF);

ui_Container5 = lv_obj_create(ui_Container1);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_height( ui_Container5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_grow( ui_Container5, 1);
lv_obj_set_x( ui_Container5, -27 );
lv_obj_set_y( ui_Container5, 131 );
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container5,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container5, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container6 = lv_obj_create(ui_Container5);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_width( ui_Container6, lv_pct(100));
lv_obj_set_height( ui_Container6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Container6, -26 );
lv_obj_set_y( ui_Container6, 110 );
lv_obj_set_align( ui_Container6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container6,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container4 = lv_obj_create(ui_Container6);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_height( ui_Container4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_grow( ui_Container4, 1);
lv_obj_set_x( ui_Container4, 5 );
lv_obj_set_y( ui_Container4, 144 );
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container4,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container7 = lv_obj_create(ui_Container4);
lv_obj_remove_style_all(ui_Container7);
lv_obj_set_width( ui_Container7, lv_pct(100));
lv_obj_set_height( ui_Container7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Container7, -28 );
lv_obj_set_y( ui_Container7, 161 );
lv_obj_set_align( ui_Container7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container7,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_currentTemp = lv_label_create(ui_Container7);
lv_obj_set_width( ui_currentTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_currentTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_currentTemp, -2 );
lv_obj_set_y( ui_currentTemp, 276 );
lv_obj_set_align( ui_currentTemp, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_currentTemp,"----");
lv_obj_set_style_text_align(ui_currentTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_currentTemp, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_currentFeelsLike = lv_label_create(ui_Container7);
lv_obj_set_width( ui_currentFeelsLike, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_currentFeelsLike, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_currentFeelsLike, -4 );
lv_obj_set_y( ui_currentFeelsLike, 248 );
lv_obj_set_align( ui_currentFeelsLike, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_currentFeelsLike,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_currentFeelsLike, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_currentFeelsLike,"----");
lv_obj_set_style_text_align(ui_currentFeelsLike, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_currentFeelsLike, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_currentFeelsLike, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_currentFeelsLike, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_currentFeelsLike, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_currentFeelsLike, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_currentTempPrecip = lv_label_create(ui_Container4);
lv_obj_set_width( ui_currentTempPrecip, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_currentTempPrecip, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_currentTempPrecip, -4 );
lv_obj_set_y( ui_currentTempPrecip, 248 );
lv_obj_set_align( ui_currentTempPrecip, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_currentTempPrecip,"----");
lv_obj_set_style_text_align(ui_currentTempPrecip, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_currentTempPrecip, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container2 = lv_obj_create(ui_Container6);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Container2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Container2, 3 );
lv_obj_set_y( ui_Container2, 7 );
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_currentHumidity = lv_label_create(ui_Container2);
lv_obj_set_width( ui_currentHumidity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_currentHumidity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_currentHumidity, -4 );
lv_obj_set_y( ui_currentHumidity, 248 );
lv_obj_set_align( ui_currentHumidity, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_currentHumidity,"----");
lv_obj_set_style_text_align(ui_currentHumidity, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_currentHumidity, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_currentWind = lv_label_create(ui_Container2);
lv_obj_set_width( ui_currentWind, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_currentWind, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_currentWind, -4 );
lv_obj_set_y( ui_currentWind, 248 );
lv_obj_set_align( ui_currentWind, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_currentWind,"----");
lv_obj_set_style_text_align(ui_currentWind, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_currentWind, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_currentGust = lv_label_create(ui_Container2);
lv_obj_set_width( ui_currentGust, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_currentGust, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_currentGust, -4 );
lv_obj_set_y( ui_currentGust, 248 );
lv_obj_set_align( ui_currentGust, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_currentGust,"----");
lv_obj_set_style_text_align(ui_currentGust, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_currentGust, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

}
