// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_screen
void ui_screen_screen_init(void);
lv_obj_t *ui_screen;
lv_obj_t *ui_Container12;
lv_obj_t *ui_Container8;
lv_obj_t *ui_duration;
lv_obj_t *ui_curtime;
lv_obj_t *ui_currentActivity;
lv_obj_t *ui_eventTitle;
lv_obj_t *ui_forecasts;
lv_obj_t *ui_Container9;
lv_obj_t *ui_futureDOW1;
lv_obj_t *ui_futureCond1;
lv_obj_t *ui_futureHL1;
lv_obj_t *ui_Container3;
lv_obj_t *ui_futureDOW2;
lv_obj_t *ui_futureCond2;
lv_obj_t *ui_futureHL2;
lv_obj_t *ui_Container10;
lv_obj_t *ui_futureDOW3;
lv_obj_t *ui_futureCond3;
lv_obj_t *ui_futureHL3;
lv_obj_t *ui_Container11;
lv_obj_t *ui_futureDOW4;
lv_obj_t *ui_futureCond4;
lv_obj_t *ui_futureHL4;
lv_obj_t *ui_current;
lv_obj_t *ui_forecastConditionsDesc;
lv_obj_t *ui_hourlyForecastChart;
lv_obj_t *ui_Container1;
lv_obj_t *ui_currentWeather;
lv_obj_t *ui_Container5;
lv_obj_t *ui_Container6;
lv_obj_t *ui_Container4;
lv_obj_t *ui_Container7;
lv_obj_t *ui_currentTemp;
lv_obj_t *ui_currentFeelsLike;
lv_obj_t *ui_currentTempPrecip;
lv_obj_t *ui_Container2;
lv_obj_t *ui_currentHumidity;
lv_obj_t *ui_currentWind;
lv_obj_t *ui_currentGust;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_screen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_screen);
}
