// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_screen
void ui_screen_screen_init(void);
extern lv_obj_t *ui_screen;
extern lv_obj_t *ui_Container12;
extern lv_obj_t *ui_Container8;
extern lv_obj_t *ui_duration;
extern lv_obj_t *ui_curtime;
extern lv_obj_t *ui_currentActivity;
extern lv_obj_t *ui_eventTitle;
extern lv_obj_t *ui_forecasts;
extern lv_obj_t *ui_Container9;
extern lv_obj_t *ui_futureDOW1;
extern lv_obj_t *ui_futureCond1;
extern lv_obj_t *ui_futureHL1;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_futureDOW2;
extern lv_obj_t *ui_futureCond2;
extern lv_obj_t *ui_futureHL2;
extern lv_obj_t *ui_Container10;
extern lv_obj_t *ui_futureDOW3;
extern lv_obj_t *ui_futureCond3;
extern lv_obj_t *ui_futureHL3;
extern lv_obj_t *ui_Container11;
extern lv_obj_t *ui_futureDOW4;
extern lv_obj_t *ui_futureCond4;
extern lv_obj_t *ui_futureHL4;
extern lv_obj_t *ui_current;
extern lv_obj_t *ui_forecastConditionsDesc;
extern lv_obj_t *ui_hourlyForecastChart;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_currentWeather;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_Container7;
extern lv_obj_t *ui_currentTemp;
extern lv_obj_t *ui_currentFeelsLike;
extern lv_obj_t *ui_currentTempPrecip;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_currentHumidity;
extern lv_obj_t *ui_currentWind;
extern lv_obj_t *ui_currentGust;
extern lv_obj_t *ui____initial_actions0;



LV_FONT_DECLARE( ui_font_lato14);
LV_FONT_DECLARE( ui_font_lato22);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
